name: Ubuntu

on:
  push:
    branches: 
        - '*'
  pull_request:
    branches: [ master-dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install libmicrohttpd
      run: |
        sudo apt-get update -qq 
        sudo apt-get install libmicrohttpd-dev

    - name: Build Faust
      run: |
        PREFIX=$(pwd)/build/pfx make
        PREFIX=$(pwd)/build/pfx make install

    - name: Upload install prefix artifact
      uses: actions/upload-artifact@v4
      with:
        name: pfx
        path: build/pfx
